# Generated by Genie
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.fields
import django.core.validators
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_url', models.URLField(blank=True, null=True)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('elements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]